### ISSUE TITLE
Getting Author from get_manga

### ISSUE THREAD

**Issue by Middlepepper** [Proxymiity/MangaDex.py#6]
Hi I'm new to this so want to check if I'm using this right.

Do you have any examples of using get_manga to get the Author uuidor  name?

When calling it with the following

```
# Import the MangaDexPy library
import MangaDexPy
cli = MangaDexPy.MangaDex()
cli.login("username", "password")

# Get manga with id b9797c5b-642e-44d9-ac40-8b31b9ae110a.
manga = cli.get_manga("b9797c5b-642e-44d9-ac40-8b31b9ae110a")

print(manga.author)
```
I get this output

`
[<MangaDexPy.author.Author object at 0x000002211EE28B20>]`

**Comment by Proxymiity** [comment]
Apologies for the late reply, I didn't receive the GH mail.

manga.author now returns an Author object, from which you can use its properties.
e.g: getting the Author's name:

```python
# Import the MangaDexPy library
import MangaDexPy
cli = MangaDexPy.MangaDex()
cli.login("username", "password")

# Get manga with id b9797c5b-642e-44d9-ac40-8b31b9ae110a.
manga = cli.get_manga("b9797c5b-642e-44d9-ac40-8b31b9ae110a")

# Get the first author from the list
author = manga.author[0]

# Print its name
print(author.name)
```
![](https://i.iya.at/WindowsTerminal_ILHfND.png)

You can check the [wiki page](https://github.com/Proxymiity/MangaDex.py/wiki/Author) for details on the Author object
